FROM node:14.15.0

ENV NODE_PATH=/app/node_modules

RUN apt-get update -qq && apt-get install -y build-essential


RUN mkdir /tmp/project

WORKDIR /tmp/project


RUN git clone https://github.com/LiveChurchSolutions/Chums.git .
RUN mv /tmp/project/ChumsApi/src/pool.ts /tmp/project/ChumsApi/src/Pool.ts
RUN mv /tmp/project/ChumsApi /app

WORKDIR /app

RUN npm install eslint-plugin-import  eslint-import-resolver-typescript  
RUN npm install -g typescript 

EXPOSE 9999


CMD ["npm run dev"]