on:
  pull_request:
    branches: [master]

name: Run Tests

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start React App
        run: |
          cd ChumsWeb
          npm install
          nohup npm start> nohup.out 2> nohup.err < /dev/null &
          cd ..

      - name: Run React Tests
        run: |
          cd CypressTests
          npm install
          npm run cy:run
